-- Run this script in Snowflake before configuring a sink connector.
-- The producer sends each customer row as JSON to the customer_events topic.

CREATE DATABASE IF NOT EXISTS CHURN_ANALYSIS;

CREATE SCHEMA IF NOT EXISTS CHURN_ANALYSIS.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS CHURN_ANALYSIS.FEATURES;
CREATE SCHEMA IF NOT EXISTS CHURN_ANALYSIS.PREDICTIONS;

USE DATABASE CHURN_ANALYSIS;

CREATE TABLE IF NOT EXISTS RAW_DATA.CUSTOMER_EVENTS (
    RECORD_CONTENT VARIANT NOT NULL,
    RECORD_METADATA VARIANT
);

CREATE OR REPLACE VIEW RAW_DATA.TELCO_CUSTOMER_CHURN AS
SELECT
    RECORD_CONTENT:customerID::VARCHAR AS CUSTOMERID,
    RECORD_CONTENT:gender::VARCHAR AS GENDER,
    RECORD_CONTENT:SeniorCitizen::NUMBER(1, 0) AS SENIORCITIZEN,
    RECORD_CONTENT:Partner::VARCHAR AS PARTNER,
    RECORD_CONTENT:Dependents::VARCHAR AS DEPENDENTS,
    RECORD_CONTENT:tenure::NUMBER(10, 0) AS TENURE,
    RECORD_CONTENT:PhoneService::VARCHAR AS PHONESERVICE,
    RECORD_CONTENT:MultipleLines::VARCHAR AS MULTIPLELINES,
    RECORD_CONTENT:InternetService::VARCHAR AS INTERNETSERVICE,
    RECORD_CONTENT:OnlineSecurity::VARCHAR AS ONLINESECURITY,
    RECORD_CONTENT:OnlineBackup::VARCHAR AS ONLINEBACKUP,
    RECORD_CONTENT:DeviceProtection::VARCHAR AS DEVICEPROTECTION,
    RECORD_CONTENT:TechSupport::VARCHAR AS TECHSUPPORT,
    RECORD_CONTENT:StreamingTV::VARCHAR AS STREAMINGTV,
    RECORD_CONTENT:StreamingMovies::VARCHAR AS STREAMINGMOVIES,
    RECORD_CONTENT:Contract::VARCHAR AS CONTRACT,
    RECORD_CONTENT:PaperlessBilling::VARCHAR AS PAPERLESSBILLING,
    RECORD_CONTENT:PaymentMethod::VARCHAR AS PAYMENTMETHOD,
    RECORD_CONTENT:MonthlyCharges::NUMBER(18, 2) AS MONTHLYCHARGES,
    RECORD_CONTENT:TotalCharges::NUMBER(18, 2) AS TOTALCHARGES,
    RECORD_CONTENT:Churn::VARCHAR AS CHURN
FROM RAW_DATA.CUSTOMER_EVENTS;

CREATE OR REPLACE VIEW FEATURES.CHURN_FEATURES AS
SELECT
    CUSTOMERID,
    TENURE,
    MONTHLYCHARGES,
    TOTALCHARGES,
    IFF(CONTRACT = 'Month-to-month', 1, 0) AS IS_MONTH_TO_MONTH,
    IFF(ONLINESECURITY = 'Yes', 1, 0) AS HAS_ONLINE_SECURITY,
    IFF(TECHSUPPORT = 'Yes', 1, 0) AS HAS_TECH_SUPPORT,
    IFF(CHURN = 'Yes', 1, 0) AS CHURN_LABEL
FROM RAW_DATA.TELCO_CUSTOMER_CHURN;

CREATE OR REPLACE TABLE PREDICTIONS.CHURN_PREDICTIONS (
    CUSTOMERID VARCHAR NOT NULL,
    PREDICTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CHURN_FLAG NUMBER(1, 0),
    CHURN_PROBABILITY FLOAT,
    RISK_LEVEL VARCHAR,
    RISK_FACTORS VARIANT,
    TENURE NUMBER(10, 0),
    MONTHLYCHARGES NUMBER(18, 2),
    TOTALCHARGES NUMBER(18, 2),
    CONTRACT VARCHAR,
    ACTUAL_CHURN_FLAG NUMBER(1, 0)
);
