-- Run this script in Snowflake before configuring a sink connector.
-- The producer sends each customer row as JSON to the customer_events topic.

CREATE DATABASE IF NOT EXISTS CHURN_ANALYSIS;

CREATE SCHEMA IF NOT EXISTS CHURN_ANALYSIS.RAW_DATA;
CREATE SCHEMA IF NOT EXISTS CHURN_ANALYSIS.FEATURES;
CREATE SCHEMA IF NOT EXISTS CHURN_ANALYSIS.PREDICTIONS;

USE DATABASE CHURN_ANALYSIS;

CREATE TABLE IF NOT EXISTS RAW_DATA.CUSTOMER_EVENTS (
    DATA VARIANT NOT NULL,
    INGESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW_DATA.TELCO_CUSTOMER_CHURN (
    CUSTOMERID VARCHAR NOT NULL,
    GENDER VARCHAR,
    SENIORCITIZEN NUMBER(1, 0),
    PARTNER VARCHAR,
    DEPENDENTS VARCHAR,
    TENURE NUMBER(10, 0),
    PHONESERVICE VARCHAR,
    MULTIPLELINES VARCHAR,
    INTERNETSERVICE VARCHAR,
    ONLINESECURITY VARCHAR,
    ONLINEBACKUP VARCHAR,
    DEVICEPROTECTION VARCHAR,
    TECHSUPPORT VARCHAR,
    STREAMINGTV VARCHAR,
    STREAMINGMOVIES VARCHAR,
    CONTRACT VARCHAR,
    PAPERLESSBILLING VARCHAR,
    PAYMENTMETHOD VARCHAR,
    MONTHLYCHARGES NUMBER(18, 2),
    TOTALCHARGES NUMBER(18, 2),
    CHURN VARCHAR
);

CREATE OR REPLACE VIEW FEATURES.CHURN_FEATURES AS
SELECT
    CUSTOMERID,
    TENURE,
    MONTHLYCHARGES,
    TOTALCHARGES,
    IFF(CONTRACT = 'Month-to-month', 1, 0) AS IS_MONTH_TO_MONTH,
    IFF(ONLINESECURITY = 'Yes', 1, 0) AS HAS_ONLINE_SECURITY,
    IFF(TECHSUPPORT = 'Yes', 1, 0) AS HAS_TECH_SUPPORT,
    IFF(CHURN = 'Yes', 1, 0) AS CHURN_LABEL
FROM RAW_DATA.TELCO_CUSTOMER_CHURN;

CREATE OR REPLACE TABLE PREDICTIONS.CHURN_PREDICTIONS (
    CUSTOMERID VARCHAR NOT NULL,
    PREDICTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CHURN_FLAG NUMBER(1, 0),
    CHURN_PROBABILITY FLOAT,
    RISK_FACTORS VARIANT
);
